os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean build test -project StockDemo/StockDemo.xcodeproj -scheme "StockDemo" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.1,name=iPhone 12" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
